<<<<<<< HEAD
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FaBeer } from 'react-icons/fa';

=======
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
>>>>>>> 416fe83 (This is the corrected version of this branch, changes from the previous one include the test-id, test expectations. the initial array is now converted to an array of objects)

export default function Home() {
  return (
    <div className={styles.container} data-testid="result">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <main className={styles.main}>

      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}