import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MenuDropdown from "../components/menu-folder/menu";

const menuList = [
  "Discorver Photos",
  "Popular Searches",
  "Leaderboard",
  "Challenges",
  "Free Videos",
  "Pexel Blog",
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <MenuDropdown 
            dropdown={menuList} 
            
            />
        </section>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}